-- Transactional audit: every fixture, including temporary access levels, is rolled back.
BEGIN;
DO $$
DECLARE leader uuid; member uuid; goal uuid; first_task uuid; second_task uuid; activity uuid; item public.portal_work_items; blocked boolean; n integer; ver integer;
BEGIN
 SELECT id INTO leader FROM profiles WHERE role='admin' LIMIT 1;
 SELECT id INTO member FROM profiles WHERE role!='admin' AND member_role!='admin' AND lower(email) NOT IN ('teraroboticstl@gmail.com','nathannovaes16@gmail.com') LIMIT 1;
 IF leader IS NULL OR member IS NULL THEN RAISE EXCEPTION 'Missing audit fixtures'; END IF;
 PERFORM set_config('request.jwt.claim.sub',leader::text,true);
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',leader,'role','authenticated')::text,true);
 SET LOCAL ROLE authenticated;
 PERFORM portal_set_access(jsonb_build_object('user_id',member,'access_level','member','status','approved'));
 PERFORM set_config('request.jwt.claim.sub',member::text,true);
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',member,'role','authenticated')::text,true);
 INSERT INTO portal_work_items(kind,title,author_id) VALUES('goal','AUDIT meta de teste',leader) RETURNING id INTO goal;
 SELECT * INTO item FROM portal_work_items WHERE id=goal;
 IF item.author_id!=member OR item.version!=1 THEN RAISE EXCEPTION 'Author ownership failed'; END IF;
 INSERT INTO portal_work_items(kind,title,goal_id,responsible_id) VALUES('task','AUDIT primeira tarefa',goal,member) RETURNING id INTO first_task;
 INSERT INTO portal_work_items(kind,title,goal_id,depends_on) VALUES('task','AUDIT segunda tarefa',goal,ARRAY[first_task]) RETURNING id INTO second_task;
 blocked:=false; BEGIN UPDATE portal_work_items SET depends_on=ARRAY[second_task] WHERE id=first_task; EXCEPTION WHEN others THEN blocked:=true; END;
 IF NOT blocked THEN RAISE EXCEPTION 'Dependency cycle accepted'; END IF;
 blocked:=false; BEGIN UPDATE portal_work_items SET status='done' WHERE id=second_task; EXCEPTION WHEN others THEN blocked:=true; END;
 IF NOT blocked THEN RAISE EXCEPTION 'Incomplete dependency accepted'; END IF;
 blocked:=false; BEGIN UPDATE portal_work_items SET author_id=leader WHERE id=goal; EXCEPTION WHEN others THEN blocked:=true; END;
 IF NOT blocked THEN RAISE EXCEPTION 'Author changed'; END IF;
 blocked:=false; BEGIN UPDATE portal_work_items SET goal_id=first_task WHERE id=second_task; EXCEPTION WHEN others THEN blocked:=true; END;
 IF NOT blocked THEN RAISE EXCEPTION 'Task used as goal'; END IF;
 blocked:=false; BEGIN UPDATE portal_work_items SET status='blocked',blocker='' WHERE id=first_task; EXCEPTION WHEN others THEN blocked:=true; END;
 IF NOT blocked THEN RAISE EXCEPTION 'Missing blocker accepted'; END IF;
 UPDATE portal_work_items SET status='done' WHERE id=first_task;
 UPDATE portal_work_items SET status='done' WHERE id=second_task;
 SELECT progress INTO n FROM portal_work_items WHERE id=second_task; IF n!=100 THEN RAISE EXCEPTION 'Completion progress failed'; END IF;
 blocked:=false; BEGIN UPDATE portal_work_items SET status='active' WHERE id=first_task; EXCEPTION WHEN others THEN blocked:=true; END;
 IF NOT blocked THEN RAISE EXCEPTION 'Completed dependent broken'; END IF;
 INSERT INTO portal_work_items(kind,title,is_historical,participants,origin) VALUES('activity','AUDIT memória histórica',true,jsonb_build_array(jsonb_build_object('user_id',member,'contribution','Teste de contribuição'),jsonb_build_object('name','Ex-integrante fictício','contribution','Sem perfil atual')),'Documento de auditoria fictício') RETURNING id INTO activity;
 blocked:=false; BEGIN UPDATE portal_work_items SET is_historical=false WHERE id=activity; EXCEPTION WHEN others THEN blocked:=true; END;
 IF NOT blocked THEN RAISE EXCEPTION 'Current activity missing date accepted'; END IF;
 blocked:=false; BEGIN UPDATE portal_work_items SET evidence='[{"url":"javascript:alert(1)"}]' WHERE id=activity; EXCEPTION WHEN others THEN blocked:=true; END;
 IF NOT blocked THEN RAISE EXCEPTION 'Invalid evidence accepted'; END IF;
 UPDATE portal_work_items SET evidence='[{"url":"https://drive.google.com/file/d/audit/view","label":"Teste"}]',archived=true WHERE id=activity;
 UPDATE portal_work_items SET archived=false WHERE id=activity;
 SELECT version INTO ver FROM portal_work_items WHERE id=activity;
 UPDATE portal_work_items SET title='AUDIT edição concorrente' WHERE id=activity AND version=ver;
 UPDATE portal_work_items SET title='AUDIT edição desatualizada' WHERE id=activity AND version=ver;
 GET DIAGNOSTICS n=ROW_COUNT; IF n!=0 THEN RAISE EXCEPTION 'Stale version overwritten'; END IF;
 SELECT count(*) INTO n FROM portal_work_audit; IF n!=0 THEN RAISE EXCEPTION 'Member reads leader audit'; END IF;
 blocked:=false; BEGIN DELETE FROM portal_work_items WHERE id=activity; EXCEPTION WHEN insufficient_privilege THEN blocked:=true; END;
 IF NOT blocked THEN RAISE EXCEPTION 'Permanent deletion allowed'; END IF;
 PERFORM portal_work_sources('AUDIT'); PERFORM portal_work_roster();
 PERFORM set_config('request.jwt.claim.sub',leader::text,true);
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',leader,'role','authenticated')::text,true);
 SELECT count(*) INTO n FROM portal_work_audit WHERE item_id=activity; IF n!=4 THEN RAISE EXCEPTION 'Create/archive/restore/update audit failed: %',n; END IF;
 PERFORM portal_set_access(jsonb_build_object('user_id',member,'access_level','trainee','status','approved'));
 PERFORM set_config('request.jwt.claim.sub',member::text,true);
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',member,'role','authenticated')::text,true);
 SELECT count(*) INTO n FROM portal_work_items WHERE id=activity; IF n!=1 THEN RAISE EXCEPTION 'Trainee read denied'; END IF;
 blocked:=false; BEGIN INSERT INTO portal_work_items(kind,title) VALUES('goal','AUDIT forbidden trainee goal'); EXCEPTION WHEN others THEN blocked:=true; END;
 IF NOT blocked THEN RAISE EXCEPTION 'Trainee insert allowed'; END IF;
 UPDATE portal_work_items SET title='AUDIT forbidden update' WHERE id=activity; GET DIAGNOSTICS n=ROW_COUNT; IF n!=0 THEN RAISE EXCEPTION 'Trainee updates item'; END IF;
 PERFORM set_config('request.jwt.claim.sub',leader::text,true);
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',leader,'role','authenticated')::text,true);
 PERFORM portal_set_access(jsonb_build_object('user_id',member,'access_level','student','status','approved'));
 PERFORM set_config('request.jwt.claim.sub',member::text,true);
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',member,'role','authenticated')::text,true);
 SELECT count(*) INTO n FROM portal_work_items; IF n!=0 THEN RAISE EXCEPTION 'External student reads internal operation'; END IF;
 blocked:=false; BEGIN PERFORM portal_work_sources(''); EXCEPTION WHEN others THEN blocked:=true; END;
 IF NOT blocked THEN RAISE EXCEPTION 'External student reads legacy sources'; END IF;
 blocked:=false; BEGIN PERFORM portal_work_roster(); EXCEPTION WHEN others THEN blocked:=true; END;
 IF NOT blocked THEN RAISE EXCEPTION 'External student reads roster'; END IF;
 RESET ROLE;
 RAISE NOTICE 'PASS: access isolation, immutable authorship, dependencies, historical participation, evidence validation, concurrency, reversible archive and leader audit';
END $$;
ROLLBACK;
