import React,{useEffect,useState} from 'react';
import {avaRequest,avaMutate} from '@/api/avaClient';
import {ACCESS_LEVELS,accessLevel,accessLabel} from '@/lib/accessLevels';
import MemberHistory from '@/components/internal/MemberHistory';
import AvaEnrollmentManagement from '@/components/ava/AvaEnrollmentManagement';
import {useAuth} from '@/lib/AuthContext';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import '@/pages/AVA.css';
export default function PortalAccessManagement({onChanged}){
 const {user,navigateToLogin}=useAuth();
 const [users,setUsers]=useState([]),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[form,setForm]=useState(null),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [enrollmentUser,setEnrollmentUser]=useState(null);
 async function load(){setError('');try{setUsers((await avaRequest('admin')).users);}catch(e){setError(e.message);}}
 useEffect(()=>{load();},[]);
 async function save(){setBusy(true);setError('');try{await avaMutate('set_access',form);setNotice('Nível de acesso atualizado.');setForm(null);setReview(false);await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="ava-shell space-y-5"><header className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-bold">Níveis de acesso do portal</h2><p className="text-sm text-gray-400 mt-2">A solicitação de AVA nunca libera a Área Interna. O administrador escolhe o nível e a autorização.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>setEnrollmentUser({})}>Gestão de matrículas</Button><Button variant="outline" onClick={load}>Atualizar usuários</Button></div></header>
 {error && <div role="alert" className="text-red-300"><p>{error}</p>{error.includes('login') && <Button className="mt-3" onClick={()=>navigateToLogin('/AdminPanel?tab=users')}>Entrar novamente com Google</Button>}</div>}{notice && <p role="status" className="text-emerald-300">{notice}</p>}
 <div className="grid sm:grid-cols-2 gap-3"><label>Buscar usuário<input className="ava-input mt-1" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nome, e-mail ou equipe" /></label><label>Filtrar nível<select className="ava-input mt-1" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos</option>{ACCESS_LEVELS.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div>
 <details className="ava-card"><summary className="cursor-pointer">O que cada nível permite</summary>{ACCESS_LEVELS.map(([key,label,description])=><p className="text-sm mt-3 text-gray-300" key={key}><strong>{label}:</strong> {description}</p>)}</details>
 {users.filter(u=>(filter==='all' || accessLevel(u)===filter) && `${u.full_name} ${u.email} ${u.access?.team_name}`.toLowerCase().includes(search.toLowerCase())).map(u=><article key={u.id} className="ava-card flex flex-wrap justify-between gap-4"><div><h3 className="font-bold">{u.full_name}</h3><p className="text-sm text-gray-400 mt-1">{u.email} · {u.access?.team_name || 'Equipe não informada'}</p><p className="text-sm mt-2">{accessLabel(u)} · {u.status==='approved'?'Autorizado':u.status==='rejected'?'Bloqueado':'Aguardando aprovação'}</p></div><div className="flex flex-wrap gap-2"><MemberHistory user={user} targetUser={u} /><Button variant="outline" onClick={()=>setEnrollmentUser(u)}>Gerenciar trilhas</Button><Button variant="outline" onClick={()=>{setReview(false);setForm({user_id:u.id,full_name:u.full_name,access_level:accessLevel(u)==='public'?'student':accessLevel(u),status:u.status || 'pending',mentor:u.access?.mentor || false});}}>Gerenciar nível</Button></div></article>)}
 {form && <Dialog open onOpenChange={open=>{if(!open && !busy)setForm(null);}}><DialogContent className="ava-shell bg-[#111217] border-white/20 text-white"><DialogHeader><DialogTitle>{review?'Confirmar nível de acesso':'Acesso de '+form.full_name}</DialogTitle><DialogDescription>{review?`${form.full_name}: ${ACCESS_LEVELS.find(([key])=>key===form.access_level)?.[1]}; ${form.status==='approved'?'autorizado':form.status==='rejected'?'bloqueado':'pendente'}.`:'Somente Membro Líder pode alterar os níveis. Alterar o nível preserva os registros do usuário.'}</DialogDescription></DialogHeader>{!review?<><label>Nível<select className="ava-input mt-1" value={form.access_level} onChange={e=>setForm({...form,access_level:e.target.value,mentor:false})}>{ACCESS_LEVELS.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><p className="text-sm text-gray-400">{ACCESS_LEVELS.find(([key])=>key===form.access_level)?.[2]}</p><label>Autorização<select className="ava-input mt-1" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="pending">Aguardando aprovação</option><option value="approved">Autorizado</option><option value="rejected">Bloqueado</option></select></label>{['member','leader'].includes(form.access_level) && <label className="flex gap-2"><input type="checkbox" checked={form.mentor} onChange={e=>setForm({...form,mentor:e.target.checked})} />Responsável por mentorias do AVA</label>}<Button onClick={()=>setReview(true)}>Revisar alteração</Button></>:<div className="flex gap-3 justify-end"><Button variant="outline" disabled={busy} onClick={()=>setReview(false)}>Voltar</Button><Button disabled={busy} onClick={save}>{busy?'Salvando…':'Confirmar alteração'}</Button></div>}</DialogContent></Dialog>}
 {enrollmentUser && <AvaEnrollmentManagement targetUser={enrollmentUser} onClose={()=>setEnrollmentUser(null)} onSaved={()=>{load();onChanged?.();}} />}
 </section>;
}


