import React,{useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {avaMutate} from '@/api/avaClient';
import {uploadToGoogleDrive} from '@/api/googleDriveClient';
import {CONTENT_TYPES,youtubeId,validateContents,safeHttps} from '@/lib/avaRules';
const labels={text:'Texto',video:'Vídeo YouTube',pdf:'PDF / apostila',image:'Imagem',checklist:'Checklist',activity:'Atividade',quiz:'Quiz'};
export default function AvaContentEditor({kind,initial,tracks,users,userId,mentorOnly,onClose,onSaved}){
  const [form,setForm]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const field=(key,value)=>setForm(old=>({...old,[key]:value}));
  const block=(id,key,value)=>field('contents',form.contents.map(b=>b.id===id?{...b,[key]:value}:b));
  async function save(e){e?.preventDefault();setBusy(true);setError('');try{if(kind==='module')validateContents(form.contents);if(kind==='track' && form.community_url && !safeHttps(form.community_url))throw new Error('Use um link HTTPS válido.');if(kind==='mentorship' && form.meeting_url && !safeHttps(form.meeting_url))throw new Error('Use um link HTTPS válido.');const r=await avaMutate(`save_${kind}`,{...form,...(kind==='mentorship'?{starts_at:new Date(form.starts_at).toISOString(),...(mentorOnly?{mentor_id:userId}:{})}:{})});field('id',r.id);setNotice('Salvo com sucesso.');onSaved();}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function upload(file,b){if(!file)return;setError('');setBusy(true);try{if(!form.id)throw new Error('Salve como rascunho antes de enviar materiais.');if(file.size>4*1024*1024)throw new Error('Para envio pela Vercel, escolha um arquivo de até 4 MB.');const media=await uploadToGoogleDrive({file,context:'ava',recordId:form.id,subfolder:kind==='track'?'Capas':'Materiais'});if(kind==='track')field('cover_file_id',media.fileId);else block(b.id,'file_id',media.fileId);setNotice('Arquivo enviado ao Drive. Salve as alterações para incluí-lo no conteúdo.');}catch(e){setError(e.message);}finally{setBusy(false);}}
  const input=(key,label,type='text')=><label className="block text-sm">{label}<input className="ava-input mt-1" type={type} value={form[key] ?? ''} onChange={e=>field(key,type==='number'?Number(e.target.value):e.target.value)} required={['title','starts_at'].includes(key)} /></label>;
  const select=(key,label,options)=><label className="block text-sm">{label}<select className="ava-input mt-1" value={form[key]} onChange={e=>field(key,e.target.value)}>{options.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>;
  return <Dialog open onOpenChange={open=>{if(!open && !busy)onClose();}}><DialogContent className="ava-shell bg-[#111217] text-white border-white/20 max-w-4xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{kind==='track'?'Editar trilha':kind==='module'?'Editar módulo':'Editar mentoria'}</DialogTitle><DialogDescription>Salve para persistir no Supabase. Rascunhos de conteúdo ficam disponíveis apenas à administração.</DialogDescription></DialogHeader><form onSubmit={save} className="space-y-5">
    {error && <p role="alert" className="text-red-300">{error}</p>}{notice && <p role="status" className="text-emerald-300">{notice}</p>}
    <div className="grid sm:grid-cols-2 gap-4">{input('title','Título')}{kind==='track'?input('subtitle','Subtítulo'):kind==='module'?select('track_id','Trilha',tracks.map(t=>[t.id,t.title])):input('area','Área da mentoria')}{kind!=='mentorship' && input('position','Ordem','number')}{kind==='module' && input('duration_minutes','Duração estimada (min)','number')}{kind==='mentorship' && <>{input('starts_at','Data e horário','datetime-local')}{input('duration_minutes','Duração (min)','number')}{input('capacity','Vagas','number')}{input('mentor_name','Nome do mentor')}{!mentorOnly && select('mentor_id','Mentor responsável',[['','Selecionar mentor'],...users.filter(u=>u.role==='admin' || (u.access?.mentor && u.access?.ava_status==='active')).map(u=>[u.id,u.full_name])])}</>}{select('status','Status',kind==='mentorship'?[['scheduled','Agendada'],['completed','Concluída'],['cancelled','Cancelada']]:[['draft','Rascunho'],['published','Publicado'],['archived','Arquivado']])}{kind==='track' && select('audience','Público',[['all','Todos os alunos AVA'],['tera','Integrantes Tera'],['external','Alunos externos']])}</div>
    <label className="block text-sm">{kind==='module'?'Resumo':'Descrição'}<textarea className="ava-input min-h-24 mt-1" value={form[kind==='module'?'summary':'description'] || ''} onChange={e=>field(kind==='module'?'summary':'description',e.target.value)} /></label>
    {kind==='track' && <>{input('community_url','Link HTTPS da comunidade')}<label className="block text-sm">Capa (imagem do Drive)<input className="ava-input mt-1" type="file" accept="image/jpeg,image/png,image/webp" disabled={busy || !form.id} onChange={e=>upload(e.target.files?.[0])} /></label><fieldset className="border border-white/10 rounded-lg p-4"><legend>Trilhas pré-requisito</legend>{tracks.filter(t=>t.id!==form.id).map(t=><label key={t.id} className="flex gap-2 py-1"><input type="checkbox" checked={form.prerequisites?.includes(t.id) || false} onChange={e=>field('prerequisites',e.target.checked?[...(form.prerequisites || []),t.id]:(form.prerequisites || []).filter(id=>id!==t.id))} />{t.title}</label>)}</fieldset></>}
    {kind==='mentorship' && input('meeting_url','Link HTTPS da reunião')}
    {kind==='module' && <><p className="text-sm text-gray-400">Alterações nos blocos criam uma nova versão e exigem nova conclusão dos alunos. Salve primeiro o módulo como rascunho para enviar PDFs e imagens.</p>{form.contents.map((b,index)=><fieldset key={b.id} className="border border-white/20 rounded-xl p-4 space-y-4"><legend className="px-2">{index+1}. {labels[b.type]}</legend><div className="flex flex-wrap gap-3 justify-between"><label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={b.required!==false} onChange={e=>block(b.id,'required',e.target.checked)} />Obrigatório para conclusão</label><div className="flex gap-2"><Button type="button" variant="outline" disabled={index===0} onClick={()=>{const arr=[...form.contents];[arr[index-1],arr[index]]=[arr[index],arr[index-1]];field('contents',arr);}}>Subir</Button><Button type="button" variant="outline" disabled={index===form.contents.length-1} onClick={()=>{const arr=[...form.contents];[arr[index+1],arr[index]]=[arr[index],arr[index+1]];field('contents',arr);}}>Descer</Button><Button type="button" variant="outline" onClick={()=>field('contents',form.contents.filter(x=>x.id!==b.id))}>Remover bloco</Button></div></div><label className="block text-sm">Título do bloco<input className="ava-input mt-1" value={b.title || ''} onChange={e=>block(b.id,'title',e.target.value)} /></label>
      {['text','activity'].includes(b.type) && <label className="block text-sm">{b.type==='text'?'Conteúdo (Markdown)':'Enunciado e instruções'}<textarea className="ava-input min-h-36 mt-1" value={b.text || ''} onChange={e=>block(b.id,'text',e.target.value)} /></label>}
      {b.type==='video' && <label className="block text-sm">URL ou ID do YouTube não listado<input className="ava-input mt-1" defaultValue={b.youtube_id || ''} onBlur={e=>block(b.id,'youtube_id',youtubeId(e.target.value) || e.target.value)} /></label>}
      {['pdf','image'].includes(b.type) && <><label className="block text-sm">Enviar {b.type==='pdf'?'PDF':'imagem'} ao Drive<input type="file" className="ava-input mt-1" accept={b.type==='pdf'?'application/pdf':'image/jpeg,image/png,image/webp'} disabled={!form.id || busy} onChange={e=>upload(e.target.files?.[0],b)} /></label><p className="text-xs text-gray-400">{b.file_id?'Arquivo vinculado: '+b.file_id:'Nenhum arquivo enviado'} · até 4 MB por envio</p></>}
      {b.type==='checklist' && <label className="block text-sm">Um item por linha<textarea className="ava-input min-h-24 mt-1" value={(b.items || []).join('\n')} onChange={e=>block(b.id,'items',e.target.value.split('\n'))} /></label>}
      {b.type==='quiz' && <><div className="grid grid-cols-2 gap-3"><label className="text-sm">Nota mínima (%)<input className="ava-input mt-1" type="number" min="1" max="100" value={b.min_score} onChange={e=>block(b.id,'min_score',Number(e.target.value))} /></label><label className="text-sm">Máximo de tentativas<input className="ava-input mt-1" type="number" min="1" max="100" value={b.max_attempts} onChange={e=>block(b.id,'max_attempts',Number(e.target.value))} /></label></div>{b.questions.map((q,i)=>{const change=(key,value)=>block(b.id,'questions',b.questions.map((x,j)=>i===j?{...x,[key]:value}:x));return <div key={i} className="rounded-lg bg-black/30 p-4 space-y-3"><label className="block text-sm">Questão {i+1}<input className="ava-input mt-1" value={q.prompt} onChange={e=>change('prompt',e.target.value)} /></label><label className="block text-sm">Alternativas (uma por linha)<textarea className="ava-input mt-1" value={q.options.join('\n')} onChange={e=>change('options',e.target.value.split('\n'))} /></label><label className="block text-sm">Alternativa correta<select className="ava-input mt-1" value={q.correct} onChange={e=>change('correct',Number(e.target.value))}>{q.options.map((o,j)=><option key={j} value={j}>{j+1}. {o}</option>)}</select></label><label className="block text-sm">Feedback pedagógico<input className="ava-input mt-1" value={q.feedback || ''} onChange={e=>change('feedback',e.target.value)} /></label><Button type="button" variant="outline" onClick={()=>block(b.id,'questions',b.questions.filter((_,j)=>i!==j))}>Remover questão</Button></div>;})}<Button type="button" variant="outline" onClick={()=>block(b.id,'questions',[...b.questions,{prompt:'',options:['',''],correct:0,feedback:''}])}>Adicionar questão</Button></>}
    </fieldset>)}<div className="flex flex-wrap gap-2">{CONTENT_TYPES.map(type=><Button key={type} variant="outline" type="button" onClick={()=>field('contents',[...form.contents,{id:crypto.randomUUID(),type,title:labels[type],required:true,...(type==='quiz'?{questions:[{prompt:'',options:['',''],correct:0}],min_score:70,max_attempts:3}:type==='checklist'?{items:['']}:type==='text'||type==='activity'?{text:''}:{})}])}>+ {labels[type]}</Button>)}</div></>}
    <div className="flex justify-end gap-3"><Button type="button" variant="outline" disabled={busy} onClick={onClose}>Fechar</Button><Button disabled={busy}>{busy?'Salvando…':'Salvar alterações'}</Button></div>
  </form></DialogContent></Dialog>;
}
