import React,{useEffect,useState} from 'react';
import {supabase} from '@/api/supabaseClient';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import '@/pages/AVA.css';
const modalities=['FLL','FTC','FRC','OBR','OBR Resgate Nível 1','OBR Resgate Nível 2','OBR Artística Nível 1','OBR Artística Nível 2'];
const empty={entry_year:'',modalities:[],responsibilities:'',history:'',seasons:'',contributions:''};
export default function MemberHistory({user,targetUser=null}){
 const [record,setRecord]=useState(null),[loaded,setLoaded]=useState(false),[open,setOpen]=useState(false),[form,setForm]=useState(empty),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const readOnly=!!targetUser;
 const eligible=!!user?.portal_internal || user?.role==='admin' || user?.member_role==='admin';
 async function load(){setError('');const {data,error:failure}=await supabase.rpc('member_history_read',targetUser?{p_user:targetUser.id}:{});if(failure){setError(failure.message);return;}setRecord(data);setForm({...empty,...data.history,entry_year:data.history?.entry_year ?? ''});setLoaded(true);}
 useEffect(()=>{if(eligible && !readOnly)load();},[user?.id,eligible]);
 if(!eligible)return null;
 async function show(){setOpen(true);await load();}
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const {data,error:failure}=await supabase.rpc('member_history_save',{p_data:{...form,entry_year:form.entry_year===''?null:Number(form.entry_year)}});if(failure)throw failure;setRecord(data);setNotice('Sua trajetória foi salva no portal.');setOpen(false);}catch(e){setError(e.message);}finally{setBusy(false);}}
 const field=(key,label,max,required=false)=><label className="block">{label}<textarea className="ava-input mt-2 min-h-24" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} maxLength={max} minLength={key==='history'?20:undefined} required={required} /><span className="text-xs text-gray-400">Até {max} caracteres{key==='history'?'; mínimo de 20':''}.</span></label>;
 return <>{readOnly?<Button variant="outline" onClick={show}>Ver trajetória</Button>:<section className="ava-shell mb-5 rounded-xl border border-red-500/25 bg-[#111217] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">{loaded && record?.required?'Complete seu cadastro: sua história na Tera':'Minha trajetória na Tera'}</h2><p className="text-sm text-gray-400 mt-1">{loaded && record?.required?'Conte como chegou ao time, suas experiências e contribuições. As informações ficam disponíveis para você e a liderança.':'Consulte e atualize sua participação nas modalidades e temporadas da equipe.'}</p></div><Button variant="outline" onClick={show}>{loaded && record?.required?'Completar cadastro':'Ver e atualizar trajetória'}</Button></div>{notice && <p role="status" className="text-emerald-300 mt-2">{notice}</p>}{error && !open && <p role="alert" className="text-red-300 mt-2">{error}</p>}</section>}
 <Dialog open={open} onOpenChange={value=>{if(!busy)setOpen(value);}}><DialogContent className="ava-shell bg-[#111217] text-white border-white/20 max-w-2xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{readOnly?'Trajetória de '+targetUser.full_name:'Minha trajetória na Tera'}</DialogTitle><DialogDescription>Registre somente informações reais. Se não souber o ano de ingresso, deixe-o em branco. Este cadastro não altera seu nível de acesso.</DialogDescription></DialogHeader>{error && <p role="alert" className="text-red-300">{error}</p>}{!loaded?<p role="status">Carregando cadastro…</p>:readOnly?<div className="space-y-4">{!record?.history?<p>Este integrante ainda não completou sua trajetória.</p>:<><p><strong>Ano de ingresso:</strong> {form.entry_year || 'Não informado'}</p><p><strong>Modalidades:</strong> {form.modalities.join(', ')}</p>{[['responsibilities','Funções e áreas'],['history','História no time'],['seasons','Temporadas e eventos'],['contributions','Contribuições e aprendizados']].map(([key,label])=><div key={key}><h3 className="font-bold">{label}</h3><p className="whitespace-pre-wrap text-gray-300">{form[key] || 'Não informado'}</p></div>)}</>}</div>:<form className="space-y-5" onSubmit={save}><label className="block">Ano de ingresso no time (opcional)<input type="number" className="ava-input mt-2" min="1900" max={new Date().getFullYear()} value={form.entry_year} onChange={e=>setForm({...form,entry_year:e.target.value})} /></label><fieldset><legend>Modalidades em que participou ou está treinando</legend><div className="grid sm:grid-cols-2 gap-3 mt-3">{modalities.map(m=><label key={m} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.modalities.includes(m)} onChange={e=>setForm({...form,modalities:e.target.checked?[...form.modalities,m]:form.modalities.filter(v=>v!==m)})} />{m}</label>)}</div><p className="text-xs text-gray-400 mt-2">Selecione pelo menos uma. Use OBR quando não souber a subcategoria.</p></fieldset>{field('responsibilities','Funções e áreas de atuação',500,true)}{field('history','Sua história dentro do time',4000,true)}{field('seasons','Temporadas, competições e projetos de que participou (opcional)',1500)}{field('contributions','Contribuições, experiências e aprendizados (opcional)',3000)}<div className="flex justify-end gap-3"><Button type="button" variant="outline" disabled={busy} onClick={()=>setOpen(false)}>Agora não</Button><Button disabled={busy || !form.modalities.length}>{busy?'Salvando…':'Salvar trajetória'}</Button></div></form>}</DialogContent></Dialog>
 </>;
}
