import React,{useState} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {RECORD_PROGRAMS} from '@/lib/modalities';
import {WORK_KINDS,WORK_STATUS,WORK_PRIORITY,teamToday,SOURCE_LABELS,sourceTitle} from '@/lib/teamOperations';
import {loadSources,saveWork} from '@/api/teamOperationsClient';
import '@/pages/AVA.css';
const blank=kind=>({kind,title:'',description:'',program:'Geral',area:'Geral',season:'',status:'planned',priority:'medium',progress:0,responsible_id:null,due_on:null,goal_id:null,task_id:null,depends_on:[],blocker:'',acceptance:'',occurred_on:['activity','meeting'].includes(kind)?teamToday():null,is_historical:false,origin:'',participants:[],evidence:[],legacy_refs:[]});
export default function WorkItemForm({initial,kind,items,roster,onClose,onSaved}){
 const [form,setForm]=useState(initial?structuredClone(initial):blank(kind));
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[referenceQuery,setReferenceQuery]=useState(''),[sources,setSources]=useState([]),[searching,setSearching]=useState(false);
 const record=['activity','meeting'].includes(form.kind);
 const set=(key,value)=>setForm(f=>({...f,[key]:value}));
 const input=(key,label,{type='text',max=200,required=false}={})=><label className="block text-sm">{label}<input className="ava-input mt-2" type={type} value={form[key]??''} required={required} maxLength={max} onChange={e=>set(key,type==='date'?(e.target.value||null):e.target.value)} /></label>;
 const text=(key,label,max=2000,required=false)=><label className="block text-sm">{label}<textarea className="ava-input mt-2 min-h-24" value={form[key]||''} required={required} maxLength={max} onChange={e=>set(key,e.target.value)} /></label>;
 const select=(key,label,options)=><label className="block text-sm">{label}<select className="ava-input mt-2" value={form[key]||''} onChange={e=>set(key,e.target.value||null)}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>;
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{await saveWork(form);onSaved();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function search(){setSearching(true);setError('');try{setSources(await loadSources(referenceQuery));}catch(e){setError(e.message);}finally{setSearching(false);}}
 return <Dialog open onOpenChange={value=>{if(!value&&!busy)onClose();}}><DialogContent className="ava-shell bg-[#111217] border-white/20 text-white max-w-3xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{initial?'Editar':'Criar'} {WORK_KINDS[form.kind].toLowerCase()}</DialogTitle><DialogDescription>Registre fatos e compromissos reais. Participantes são quem realizou a atividade; o autor é quem registra. Os vínculos preservam os cadastros existentes.</DialogDescription></DialogHeader>
 <form onSubmit={submit} className="space-y-5">
 {error&&<p role="alert" className="text-red-300">{error}</p>}
 {input('title','Título',{required:true})}
 {text('description',form.kind==='meeting'?'Pauta, discussões, decisões e encaminhamentos':'Descrição e contexto',12000)}
 <div className="grid sm:grid-cols-2 gap-4">{select('program','Modalidade',[...RECORD_PROGRAMS,'Geral'].map(v=>[v,v]))}{input('area','Área de atuação',{max:100,required:true})}{input('season','Temporada / ciclo (opcional)',{max:120})}
 {select('responsible_id',record?'Responsável pelo acompanhamento (opcional)':'Responsável',[['','Não definido'],...roster.map(u=>[u.id,u.full_name])])}
 {!record&&<>{select('status','Status',Object.entries(WORK_STATUS))}{select('priority','Prioridade',Object.entries(WORK_PRIORITY))}{input('due_on','Prazo (opcional)',{type:'date'})}</>}
 {form.kind!=='goal'&&select('goal_id','Vincular a uma meta',[['','Sem vínculo'],...items.filter(i=>i.kind==='goal').map(i=>[i.id,i.title+(i.archived?' (arquivada)':'')])])}
 {record&&select('task_id','Vincular a uma tarefa',[['','Sem vínculo'],...items.filter(i=>i.kind==='task').map(i=>[i.id,i.title+(i.archived?' (arquivada)':'')])])}
 </div>
 {form.kind==='goal'&&text('acceptance','Critério de sucesso e evidência esperada')}
 {form.kind==='task'&&<><label className="block text-sm">Progresso declarado ({form.progress}%)<input aria-label="Progresso declarado" type="range" min="0" max="100" step="5" className="w-full mt-3" value={form.progress} onChange={e=>set('progress',Number(e.target.value))} /></label>{text('blocker','Bloqueio, dependência externa ou dificuldade',1500,form.status==='blocked')}
 <fieldset className="ava-card"><legend>Depende destas tarefas</legend><p className="text-xs text-gray-400 mb-3">A conclusão exige que as dependências estejam concluídas. Ciclos são impedidos pelo banco.</p><div className="space-y-2 max-h-48 overflow-y-auto">{items.filter(i=>i.kind==='task'&&i.id!==form.id&&!i.archived).map(i=><label key={i.id} className="flex gap-2 text-sm"><input type="checkbox" checked={form.depends_on.includes(i.id)} onChange={e=>set('depends_on',e.target.checked?[...form.depends_on,i.id]:form.depends_on.filter(id=>id!==i.id))} />{i.title} · {WORK_STATUS[i.status]}</label>)}{!items.some(i=>i.kind==='task'&&i.id!==form.id&&!i.archived)&&<p className="text-sm text-gray-400">Nenhuma outra tarefa disponível.</p>}</div></fieldset></>}
 {record&&<><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.is_historical} onChange={e=>setForm(f=>({...f,is_historical:e.target.checked,occurred_on:e.target.checked?null:teamToday(),participants:e.target.checked?f.participants:f.participants.filter(p=>p.user_id)}))} />Registro histórico (atividade de temporada anterior)</label>
 {input('occurred_on',form.is_historical?'Data real da atividade (deixe em branco se desconhecida)':'Data da atividade',{type:'date',required:!form.is_historical})}{text('origin','Origem / contexto das informações (opcional)',1500)}
 <fieldset className="ava-card"><legend>Participantes e contribuições</legend><p className="text-xs text-gray-400 mb-3">Uma atividade coletiva é registrada uma única vez. Não atribua contribuições que você não conhece.</p>
 <select aria-label="Adicionar participante" className="ava-input" value="" onChange={e=>{const u=roster.find(u=>u.id===e.target.value);if(u&&!form.participants.some(p=>p.user_id===u.id))set('participants',[...form.participants,{user_id:u.id,name:u.full_name,contribution:''}]);}}><option value="">Adicionar integrante</option>{roster.map(u=><option key={u.id} value={u.id}>{u.full_name}</option>)}</select>
 {form.is_historical&&<Button type="button" variant="outline" className="mt-3" onClick={()=>set('participants',[...form.participants,{user_id:null,name:'',contribution:''}])}>Adicionar participante histórico sem cadastro</Button>}
 {form.participants.map((p,index)=><div key={p.user_id||index} className="border-t border-white/10 mt-4 pt-4 space-y-2">{p.user_id?<strong className="text-sm">{roster.find(u=>u.id===p.user_id)?.full_name||p.name||'Integrante fora da lista atual'}</strong>:<label className="block text-sm">Nome do participante histórico<input required minLength="3" maxLength="150" className="ava-input mt-2" value={p.name} onChange={e=>set('participants',form.participants.map((v,j)=>j===index?{...v,name:e.target.value}:v))} /></label>}
 <label className="block text-sm">Contribuição individual (opcional)<textarea maxLength="2000" className="ava-input mt-2" value={p.contribution} onChange={e=>set('participants',form.participants.map((v,j)=>j===index?{...v,contribution:e.target.value}:v))} /></label><Button type="button" variant="outline" onClick={()=>set('participants',form.participants.filter((_,j)=>j!==index))}>Remover participante</Button></div>)}
 </fieldset></>}
 <fieldset className="ava-card"><legend>Evidências</legend><p className="text-xs text-gray-400 mb-3">Vincule arquivos já enviados ao Drive institucional ou vídeos. Este formulário mantém as permissões originais dos arquivos.</p>
 {form.evidence.map((ev,index)=><div key={index} className="space-y-2 mb-4"><label className="block text-sm">Descrição da evidência<input className="ava-input mt-1" maxLength="200" value={ev.label} onChange={e=>set('evidence',form.evidence.map((v,j)=>j===index?{...v,label:e.target.value}:v))} /></label><label className="block text-sm">Link do Drive, Documentos ou YouTube<input type="url" required className="ava-input mt-1" value={ev.url} maxLength="1800" onChange={e=>set('evidence',form.evidence.map((v,j)=>j===index?{...v,url:e.target.value}:v))} /></label><Button type="button" variant="outline" onClick={()=>set('evidence',form.evidence.filter((_,j)=>j!==index))}>Remover vínculo</Button></div>)}
 <Button type="button" variant="outline" disabled={form.evidence.length>=20} onClick={()=>set('evidence',[...form.evidence,{label:'',url:''}])}>Adicionar evidência</Button></fieldset>
 <fieldset className="ava-card"><legend>Relacionar registros já existentes</legend><div className="flex flex-wrap gap-2"><input aria-label="Buscar referência existente" maxLength="160" className="ava-input flex-1" value={referenceQuery} onChange={e=>setReferenceQuery(e.target.value)} placeholder="Título ou trecho do registro" /><Button type="button" variant="outline" disabled={searching} onClick={search}>{searching?'Buscando…':'Buscar referências'}</Button></div>
 {form.legacy_refs.map(ref=><div key={ref.kind+ref.id} className="flex flex-wrap items-center justify-between gap-2 mt-3"><p className="text-sm">{SOURCE_LABELS[ref.kind]} · {ref.title||ref.id}</p><Button type="button" variant="outline" onClick={()=>set('legacy_refs',form.legacy_refs.filter(r=>r.kind!==ref.kind||r.id!==ref.id))}>Desvincular</Button></div>)}
 <div className="max-h-48 overflow-y-auto mt-3 space-y-2">{sources.map(s=><Button key={s.kind+s.id} type="button" variant="outline" className="w-full justify-start whitespace-normal h-auto text-left" disabled={form.legacy_refs.length>=20||form.legacy_refs.some(r=>r.kind===s.kind&&r.id===s.id)} onClick={()=>set('legacy_refs',[...form.legacy_refs,{kind:s.kind,id:s.id,title:sourceTitle(s)}])}>{SOURCE_LABELS[s.kind]}: {sourceTitle(s)}</Button>)}</div></fieldset>
 <div className="flex gap-3 justify-end"><Button type="button" variant="outline" disabled={busy} onClick={onClose}>Cancelar</Button><Button disabled={busy}>{busy?'Salvando…':'Salvar '+WORK_KINDS[form.kind].toLowerCase()}</Button></div>
 </form></DialogContent></Dialog>;
}
